language: ruby
cache: bundler
rvm:
  - 2.3.5
services:
  - elasticsearch
before_install:
  - gem update bundler
  - curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.4.0.deb && sudo dpkg -i --force-confnew elasticsearch-1.4.0.deb && sudo service elasticsearch restart
install:
  - bundle install
script: bundle exec rake test
