language: ruby
cache: bundler
rvm:
  - 2.1
services:
  - elasticsearch
before_install:
  - gem update bundler  
install:
  - bundle install
before_script:
  - "elasticsearch -v"
script: bundle exec rake test
